### ISSUE TITLE
Zod errors when executing procedures.

### ISSUE THREAD

**Issue by agulencina96** [aidansunbury/trpc-ui#27]
**Describe the bug**

When trying to execute any procedure, Zod takes it as if none of the parameters had been sent and throws 404.

**To Reproduce**
1. having a server with fastify v4
2. register a route get 
```ts
app.get('/panel', async (req, res) => {
      res
        .status(200)
        .type('text/html')
        .send(
          renderTrpcPanel(appRouter, {
            url: 'http://localhost:6902/api',
          }),
        );
    })
```
to render the panel
3. try to execute any procedure with inputs

**Expected behavior**
that the executed procedure correctly receives the parameters

**Screenshots**

![image](https://github.com/user-attachments/assets/5c6eaaf6-602b-4f24-ac28-98ed658974f4)
![image](https://github.com/user-attachments/assets/89ae135a-b1d9-4970-a7b8-bb06fd9a41cf)

**Additional context**
I think the problem could be due to the way the payload is loaded using first the “json” key before the values.

**Comment by aidansunbury** [comment]
Hey @agulencina96 I think you are right that is probably has something to do with the "json" key, as #26 is also having problems with it. However, I was able to get the panel running using fastify in [this repo](https://github.com/aidansunbury/fastify-trpc-ui-test) which is based on the [trpc fastify example](https://github.com/trpc/trpc/tree/next/examples/fastify-server). 

```ts
const server = fastify({ logger: dev });

server.get("/panel", async (_, reply) => {
		const html = renderTrpcPanel(appRouter, {
			url: "http://localhost:2022/trpc",
			transformer: "superjson",
		});
		reply.type("text/html").send(html);
	});
```
I think it is possible the issue could have something to do with superjson, but I'm honestly not sure since I'm not super familiar with fastify.

Could you create a repo that reproduces the issue, or at the very least send the file in which you initialized trpc and the fastify server? I doubt I'll be able to debug and fix the issue if I can't reproduce it.

**Comment by lcjnil** [comment]
I'm using express and I got the same error

**Comment by aidansunbury** [comment]
Hey @lcjnil, first can you try updating to the the [1.0.5](https://www.npmjs.com/package/trpc-ui) release and see if your issue persists. It is possible that the changes in #28 fixed your issue.

If not, it would be super helpful if you could make a minimal reproduction of your issue in a public repo or on something like stackblitz? It would help a ton in solving the issue!

**Comment by sachinahya** [comment]
Just to mention I am also having similar issues but only when I am not using superjson.

I can confirm using 1.0.6 release works fine when I configure tRPC with superjson.

I think the problem lies in that, when superjson is enabled, the input needs to be in this format nested under a `json` key:

```
{"0":{"json":{"id":"abc"}}}
```

Whereas without superjson, the `json` key needs to be omitted:

```
{"0":{"id":"abc"}}
```
